<#
# ============================================================
# Data Insight Platform - One-click Docker Startup
# ============================================================
# Usage:
#   .\start.ps1              # Start in dev mode (hot reload, default)
#   .\start.ps1 -Mode prod   # Start in production mode (built images)
#   .\start.ps1 -Force       # Regenerate config files from templates
#
# What it does:
#   1. Checks Docker / docker compose availability and daemon status
#   2. Checks required ports
#   3. Generates configs if missing (docker-compose.yml, .env, backend/.env)
#      - random passwords / secret key are generated automatically
#      - existing configs are kept unless -Force is passed
#   4. Starts services via docker compose --profile <mode> up -d --build
#   5. Waits for backend readiness and prints access URLs
#
# Note: system starts with an EMPTY database (no sample data).
#       For AI analysis, edit backend/.env and fill OPENAI_API_KEY.
# ============================================================
#>

param(
    [ValidateSet("dev", "prod")]
    [string]$Mode = "dev",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$root = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($root)) { $root = (Get-Location).Path }

Write-Host ""
Write-Host "=== Data Insight Platform Startup ===" -ForegroundColor Cyan
Write-Host "Mode: $Mode (root: $root)"
Write-Host ""

# ------------------------------------------------------------
# 1. Check Docker environment
# ------------------------------------------------------------
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Host "[ERROR] Docker not found. Please install Docker Desktop first." -ForegroundColor Red
    Write-Host "        https://www.docker.com/products/docker-desktop/" -ForegroundColor Red
    exit 1
}

# 必须使用 docker compose v2（v1 不支持 --profile）
docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] docker compose v2 is not available. Please upgrade Docker Desktop / docker-compose." -ForegroundColor Red
    exit 1
}
$compose = "docker compose"

docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Docker daemon is not running. Please start Docker Desktop." -ForegroundColor Red
    exit 1
}
Write-Host "[OK] Docker is available ($compose)." -ForegroundColor Green

# ------------------------------------------------------------
# 2. Check ports
# ------------------------------------------------------------
$ports = if ($Mode -eq "prod") { @(80, 8000) } else { @(8000, 5173, 5174, 5433, 6379, 9000, 9001, 8123) }
foreach ($p in $ports) {
    $conn = Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue
    if ($conn) {
        $pidList = ($conn.OwningProcess | Sort-Object -Unique) -join ", "
        Write-Host "[ERROR] Port $p is already in use (PID: $pidList). Please free it and retry." -ForegroundColor Red
        exit 1
    }
}
Write-Host "[OK] Required ports are free." -ForegroundColor Green

# ------------------------------------------------------------
# 3. Generate configs (idempotent)
# ------------------------------------------------------------
function New-RandomPassword([int]$len = 16) {
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    $bytes = New-Object byte[] $len
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $sb = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $len; $i++) {
        [void]$sb.Append($chars[$bytes[$i] % $chars.Length])
    }
    return $sb.ToString()
}

# 3.1 docker-compose.yml
$composeFile = Join-Path $root "docker-compose.yml"
if ((Test-Path $composeFile) -and -not $Force) {
    Write-Host "[INFO] docker-compose.yml exists, keeping it."
}
else {
    Copy-Item (Join-Path $root "docker-compose.example.yml") $composeFile -Force
    Write-Host "[OK] docker-compose.yml generated from template." -ForegroundColor Green
}

# 3.2 root .env (for compose interpolation)
$rootEnv = Join-Path $root ".env"
if ((Test-Path $rootEnv) -and -not $Force) {
    Write-Host "[INFO] .env exists, keeping it."
}
else {
    $pgPass = New-RandomPassword
    $redisPass = New-RandomPassword
    $chPass = New-RandomPassword
    $minioKey = "minioadmin"
    $minioSecret = New-RandomPassword
    @"
# Auto-generated by start.ps1 - used by docker-compose interpolation
POSTGRES_USER=datainsight
POSTGRES_PASSWORD=$pgPass
REDIS_PASSWORD=$redisPass
CLICKHOUSE_USER=default
CLICKHOUSE_PASSWORD=$chPass
MINIO_ACCESS_KEY=$minioKey
MINIO_SECRET_KEY=$minioSecret
"@ | Set-Content -Path $rootEnv -Encoding UTF8
    Write-Host "[OK] .env generated with random passwords." -ForegroundColor Green
}

# 3.3 backend/.env
$backendEnv = Join-Path $root "backend\.env"
$backendEnvExample = Join-Path $root "backend\.env.example"
if ((Test-Path $backendEnv) -and -not $Force) {
    Write-Host "[INFO] backend/.env exists, keeping it."
}
else {
    if (-not (Test-Path $backendEnvExample)) {
        Write-Host "[ERROR] backend/.env.example not found." -ForegroundColor Red
        exit 1
    }
    $adminPass = New-RandomPassword 12
    $content = Get-Content -Path $backendEnvExample -Raw
    $content = $content -replace "your-secret-key-change-in-production", (New-RandomPassword 32)
    $content = $content -replace "your-admin-password", $adminPass
    # Keep OPENAI_API_KEY placeholder for user to fill in later
    $content = $content -replace "your-minio-access-key", "minioadmin"
    $content = $content -replace "your-minio-secret-key", (New-RandomPassword)
    $content = $content -replace "your-clickhouse-password", (New-RandomPassword)
    Set-Content -Path $backendEnv -Value $content -Encoding UTF8
    Write-Host "[OK] backend/.env generated from template." -ForegroundColor Green
    Write-Host "[ADMIN] username: admin  password: $adminPass  (keep it safe)" -ForegroundColor Yellow
}

# ------------------------------------------------------------
# 3.4 配置 AI 分析（可选）：交互式输入 API Key 并测试连接
# ------------------------------------------------------------
function Test-AIConnection {
    # 发送最小 chat 请求，验证 Key / 服务地址 / 模型名是否有效（消耗约 1 token）
    param([string]$Base, [string]$Model, [string]$Key)
    $body = @{
        model      = $Model
        messages   = @(@{ role = "user"; content = "ping" })
        max_tokens = 1
    } | ConvertTo-Json -Depth 5
    $headers = @{ Authorization = "Bearer $Key" }
    try {
        $null = Invoke-RestMethod -Uri "$($Base.TrimEnd('/'))/chat/completions" -Headers $headers -Method Post -Body $body -ContentType "application/json" -TimeoutSec 20
        return $true
    }
    catch {
        Write-Host "  [FAIL] 连接失败: $($_.Exception.Message)" -ForegroundColor Yellow
        return $false
    }
}

function Set-EnvValue {
    # 按行替换 .env 中某个变量的值（变量不存在则追加；$ 已转义防止正则组引用）
    param([string]$Content, [string]$Name, [string]$Value)
    $escaped = $Value.Replace('$', '$$')
    if ($Content -match "(?m)^$([regex]::Escape($Name))=") {
        return ($Content -replace "(?m)^$([regex]::Escape($Name))=.*$", "$Name=$escaped")
    }
    return ($Content.TrimEnd() + "`r`n$Name=$escaped")
}

Write-Host ""
Write-Host "=== AI 分析配置（可选）===" -ForegroundColor Cyan
$aiContent = Get-Content -Path $backendEnv -Raw
$currentKey = ""
if ($aiContent -match '(?m)^OPENAI_API_KEY=(.*)$') { $currentKey = $matches[1].Trim() }

if ($currentKey -and $currentKey -notmatch 'your-') {
    Write-Host "[INFO] OPENAI_API_KEY 已配置，跳过。如需更换，请手动编辑 backend/.env 后重启 backend 容器。" -ForegroundColor Green
}
else {
    $answer = Read-Host "是否现在配置 AI 分析 API Key？(Y/n)"
    if ($answer -ne 'n' -and $answer -ne 'N') {
        $aiBase = Read-Host "AI 服务地址（默认 https://api.deepseek.com/v1）"
        if ([string]::IsNullOrWhiteSpace($aiBase)) { $aiBase = "https://api.deepseek.com/v1" }
        $aiModel = Read-Host "模型名（默认 deepseek-chat）"
        if ([string]::IsNullOrWhiteSpace($aiModel)) { $aiModel = "deepseek-chat" }

        $configured = $false
        for ($attempt = 1; $attempt -le 3 -and -not $configured; $attempt++) {
            if ($attempt -gt 1) {
                $retry = Read-Host "是否重试输入 Key？(Y/n)"
                if ($retry -eq 'n' -or $retry -eq 'N') { break }
            }
            Write-Host "请输入 API Key（输入过程不显示）：" -NoNewline
            $secure = Read-Host -AsSecureString
            $ptr = [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
            $aiKey = [System.Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
            [System.Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
            if ([string]::IsNullOrWhiteSpace($aiKey)) {
                Write-Host "[WARN] 未输入 Key，跳过配置。" -ForegroundColor Yellow
                break
            }

            Write-Host "  正在测试连接（$aiBase / $aiModel）..."
            if (Test-AIConnection -Base $aiBase -Model $aiModel -Key $aiKey) {
                $aiContent = Set-EnvValue -Content $aiContent -Name "OPENAI_API_KEY" -Value $aiKey
                $aiContent = Set-EnvValue -Content $aiContent -Name "OPENAI_API_BASE" -Value $aiBase
                $aiContent = Set-EnvValue -Content $aiContent -Name "OPENAI_MODEL" -Value $aiModel
                Set-Content -Path $backendEnv -Value $aiContent -Encoding UTF8
                Write-Host "[OK] API Key 验证通过并已写入 backend/.env。" -ForegroundColor Green
                $configured = $true
            }
            else {
                Write-Host "  Key / 地址 / 模型有误（第 $attempt 次）。" -ForegroundColor Yellow
            }
        }
        if (-not $configured) {
            Write-Host "[WARN] 未完成配置，可稍后手动编辑 backend/.env 的 OPENAI_API_KEY 并重启 backend 容器。" -ForegroundColor Yellow
        }
    }
}

# ------------------------------------------------------------
# 4. Start services
# ------------------------------------------------------------
Write-Host ""
Write-Host "[INFO] Starting services ($Mode profile). First build may take a while..." -ForegroundColor Yellow
Push-Location $root
try {
    Invoke-Expression "$compose --profile $Mode up -d --build"
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[ERROR] docker compose up failed. See logs above." -ForegroundColor Red
        exit 1
    }
}
finally {
    Pop-Location
}

# ------------------------------------------------------------
# 5. Wait for backend readiness
# ------------------------------------------------------------
Write-Host ""
Write-Host "[INFO] Waiting for backend to be ready..." -ForegroundColor Yellow
$ready = $false
for ($i = 0; $i -lt 60; $i++) {
    try {
        $res = Invoke-WebRequest -Uri "http://localhost:8000/docs" -UseBasicParsing -TimeoutSec 3
        if ($res.StatusCode -eq 200) { $ready = $true; break }
    }
    catch {
        # backend not up yet, keep waiting
    }
    Start-Sleep -Seconds 2
}
if ($ready) {
    Write-Host "[OK] Backend is ready." -ForegroundColor Green
}
else {
    Write-Host "[WARN] Backend not ready within 120s. Check logs: $compose logs backend" -ForegroundColor Yellow
}

# ------------------------------------------------------------
# 6. Print access URLs
# ------------------------------------------------------------
Write-Host ""
Write-Host "=== Access URLs ===" -ForegroundColor Cyan
if ($Mode -eq "dev") {
    Write-Host "  User UI:    http://localhost:5173"
    Write-Host "  Admin UI:   http://localhost:5174/admin.html"
}
else {
    Write-Host "  User UI:    http://localhost"
    Write-Host "  Admin UI:   http://localhost/admin.html"
}
Write-Host "  API Docs:   http://localhost:8000/docs"
Write-Host ""
Write-Host "The system starts with an empty database (no sample data)." -ForegroundColor Yellow
Write-Host "Stop services: docker compose --profile $Mode down" -ForegroundColor Yellow
Write-Host ""
